### ISSUE TITLE
More scripts？

### ISSUE THREAD

**Issue by wabyking** [unarxiv/crosstalk-dataset#1]
Do you have any plans or suggestions to collect a large-scale dataset of crosstalk scripts? Because the current one is too small to conduct any research works.

**Comment by xzyaoi** [comment]
@wabyking I am really sorry for the late reply as I am not working on this repository anymore.

In the past, this repository is collected by a scraper and cleaned manually. Hence, I would suggest that you could probably follow the same pattern. You can search with "相声 脚本" and perform some simple text-replacement for cleaning.

Unfortunately, I cannot provide any further assistance on this, but I tried it and it is doable. It would be really exciting if there is more research on this.

Best,
Xiaozhe

**Comment by wabyking** [comment]
Thanks for your kind reply.
